### ISSUE TITLE
GLUG logo needs to be replaced with the new logo

### ISSUE THREAD

**Issue by divyanshu013** [glugnith/glupaste#3]
![screenshot 14](https://cloud.githubusercontent.com/assets/6682655/7216519/e5647c52-e61f-11e4-9d82-2ad41009c027.png)

**Comment by Rishabh04-02** [comment]
there is no glug logo at the site http://glug.nith.ac.in:5000/

**Comment by divyanshu013** [comment]
This repo is deprecated @Rishabh04-02. The issue was pertaining the old gluPaste.
